### ISSUE TITLE
Bizzare crash in com.otakusenpai.aghora.core.helpers.hasPlgCommand

### ISSUE THREAD

**Issue by OtakuSenpai** [OtakuSenpai/AghoraBot#3]
Please give the following details while trying to open a issue:-

1) The message that triggered the error or issue
    :Nawab!~me@117.194.195.243 PRIVMSG #nawab-test : /o\
2) The network and any other data associated with the message's origin
     java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at com.otakusenpai.aghora.core.helpers.ConstantsKt.hasPlgCommand(Constants.kt:395)
	at com.otakusenpai.aghora.core.bot.BasicBot$handleMessages$1.doResume(BasicBot.kt:222)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
	at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:25)
	at kotlinx.coroutines.experimental.EventLoopBase.processNextEvent(EventLoop.kt:147)
	at kotlinx.coroutines.experimental.BlockingCoroutine.joinBlocking(Builders.kt:244)
	at kotlinx.coroutines.experimental.BuildersKt.runBlocking(Builders.kt:185)
	at kotlinx.coroutines.experimental.BuildersKt.runBlocking$default(Builders.kt:175)
	at com.otakusenpai.aghora.core.bot.BasicBot.handleMessages(BasicBot.kt:196)
	at com.otakusenpai.aghora.core.bot.BasicBot$Connect$1$two$1.doResume(BasicBot.kt:114)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
	at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:25)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by OtakuSenpai** [comment]
Fixed the crash, made the bot parse messages if only the message contains more than 2 letters.
